---
title: "Chilling Tale"
author: "Thomas F. O'Boyle"
date: "May 07, 1990"
output: pdf_document
---

## GE Refrigerator Woes Illustrate the Hazards In Changing a Product

## Firm Pushed Development Of Compressor Too Fast, Failed to Test Adequately

## Missing: the `Magical Balance'

The Wall Street Journal, PAGE A1 (Copyright (c) 1990, Dow Jones & Co., Inc.)

LOUISVILLE, Ky. - General Electric Co. began making a new refrigerator model in 1986 - and thought it had a breakthrough. Its engineers had designed a revolutionary compressor and a futuristic factory to make it.

GE was so certain the new product would leapfrog Japanese rivals that it staked its entire $2 billion refrigerator business on the innovative design of the compressor - the pump that creates cold air, as crucial to a refrigerator as an engine to a car. The old compressor was scrapped. At the appliance division's headquarters here, managers were setting out to prove that America could still be a world leader in manufacturing.

But today, the very managers who had defiantly refused to buy compressors from overseas rivals are doing exactly that. Now, when GE assembles refrigerators at its plants in Louisville, Indiana and Alabama, it uses compressors purchased from six suppliers, five of them foreign.

The project, says Roger Schipke, the division's former chief, "was your worst nightmare come true. I don't even want to think about it anymore." Mr. Schipke now is the president of Ryland Group Inc., a Columbia, Md., home builder.

GE's new compressor flopped so badly that the company had to take a $450 million pretax charge in 1988. And since early last year, it has voluntarily replaced nearly 1.1 million defective compressors.

At first, it was changing 5,000 a week. Even now, the process goes on. In a kitchen in rural Beaver County near Pittsburgh, serviceman Paul Jackson yanks a defective compressor from the back of an almond-colored refrigerator . He replaces it with one made in Italy. The changeover takes 90 minutes. Still to be repaired: as many as 200,000 refrigerators, many of which can't be located.

The full story of GE's fiasco has never been told. After interviews on the matter with more than 30 current and former GE employees, the tale that emerges offers a lesson for all manufacturers.

GE's travails don't show that America should stop trying to compete with the Japanese - who, as GE later discovered, had similar troubles with the same compressor design. Rather, the story illustrates how even a company with GE's vast resources and formidable skills can fall into trouble if it goes too far, too fast. Pioneering new technology carries great risks along with the possibility of great rewards, and the risks may indicate that a manufacturer should phase in a new product gradually.

"You have to have that magical balance between getting it right and getting it fast. Obviously, we didn't have that," says Stephen Holmes, who was one of several GE managers that supervised the refrigerator 's design and who now is a vice president at rival Whirlpool Corp. Adds Dietrich Huttenlocher, a former GE technical trouble-shooter who was part of the research team that investigated the failure: "GE learned a hard lesson: Don't cut corners on the testing."

Blunders were committed at practically every level. In designing the compressor, engineers made some bad assumptions and then failed to ask the right questions. Managers, eager to cut costs, forced the engineers to accelerate "life testing" of the compressor, curtailed field testing and rushed into production.

Ultimately, the problems stemmed from poor corporate communication. Several low-level salaried employees at GE - the technicians who did the actual pre-production testing - say they suspected that the compressor might be defective and told their superiors. But senior executives, six levels removed, heard only good news.

In retrospect, Richard Burke, the appliance division's current chief of technology and manufacturing, says he would have done it differently. "I'd have gone and found the lowest damn level people we had . . . and just sat down in their little cubbyholes and asked them `How are things today?'"

How could such errors be made at GE, widely acclaimed for its management?

From the start, GE was under pressure. In the fall of 1981, when the compressor saga began, the appliance division's market share - and profits - were falling.

What's more, GE was using antiquated methods to make refrigerators, the core of the appliance group. GE's compressor plant - Building 4 in the Appliance Park complex that employs 12,300 in Louisville - was relying on 1950s technology and lots of manpower. Making a single piston took 220 steps. Even simple grinding operations were done by hand. GE took 65 minutes of labor to make a compressor. Rivals in Japan and Italy made theirs in just 25 minutes and, because of lower labor rates, at half the cost.

Ira C. Magaziner, a Providence, R.I., consultant brought in for advice, handed down a somber verdict: either buy compressors abroad or find a way to build better ones. (Mr. Magaziner's findings are recounted in his 1989 management book, "The Silent War," which praised GE's efforts to build the new compressor.)

After a fierce internal debate, appliance-division executives decided to build their own. On Sept. 1, 1983, Mr. Schipke and two senior engineers flew to Connecticut to sell the idea to GE Chairman Jack Welch. (Mr. Welch declined to be interviewed.) The division executives proposed that GE commit $120 million to build a factory in Columbia, Tenn., about 50 miles south of Nashville. The factory would make a newly designed compressor - the rotary - a technology that GE had invented but used only in air conditioners.

"We told them it wasn't a moonshot. We knew how to make rotaries. We'd made 12 million of them in air conditioners," Mr. Schipke recalls. Mr. Welch agreed. So did directors at GE's next board meeting.

In reality, though, the rotary was a moonshot in refrigerators. At first glance, the new design seemed ideal. It weighed less and was more energy-efficient than old-fashioned reciprocating compressors, which had three times as many parts. The new design and new factory would halve GE's compressor-production costs.

But Peter Davey, a former chief design engineer for refrigerators, cites "a whole lot of reasons you don't go into a rotary compressor fast." Mr. Davey, who retired in 1981, and others had long argued that rotaries weren't good in refrigerators.

Rotaries run hotter than traditional compressors. That isn't a problem in most air conditioners; fast-flowing coolant cools the compressor. But in a refrigerator , which typically runs four times as many hours as an air conditioner in a year's time, coolant flows one-tenth as fast. And excessive heat can kill a compressor.

Even in air conditioners, moreover, rotaries aren't perfect. Introduced in 1957, they initially caused trouble. Gradually, the bugs were worked out. But in the mid-1970s, GE had to abandon rotaries in its big air conditioners. The compressors broke down in hot climates; failures in Saudi Arabia and Arizona eventually persuaded management to return to reciprocating compressors in the big units.

Despite these portents, GE's refrigerator managers and engineers were fixated on other issues. One was noise. Fearful that the rotary's high-pitched whine would spook consumers, executives argued over ways to mask it. Managers and consumer test panels spent hours listening to the new refrigerators.

Another time-consuming issue concerned manufacturing. The new design required the key parts to work together at a friction point of fifty-millionths of an inch - about one-hundredth the width of a human hair. Nothing had ever been mass produced at such an extreme tolerance.

The manufacturing engineers, led by Tom Blunt, felt sure they could do it. But they needed a little help - and the design engineers, working across the hall, provided it. The compressor that GE ultimately manufactured was nearly identical to the rotary used in air conditioners. There was one change, though, and it turned out to be disastrous.

Two small parts inside the compressor were made out of a new material, powdered metal, rather than the hardened steel and cast iron in air conditioners. Powdered metal - made by fusing a fine powder into solid metal through pressure - pleased two groups: manufacturing engineers, because it would be more easily machined to extreme tolerance, and managers, because it cut machining costs.

However, powdered metal had been tried a decade earlier in air conditioners and "didn't hold up," says Burr Stanton, an evaluation engineer who supervised tests on it in the early 1970s. He and others say that information was passed on to the design engineers. But they didn't listen, he says. "The guys who were designing it were new to compressors. They figured they were smarter and thought it wouldn't happen to them," Mr. Stanton explains.

The engineers who did the actual design were assembled by the appliance division's chief design engineer, John Truscott. Before coming to Louisville, Mr. Truscott was considered one of GE's top technologists; he had been, for example, on an aerospace team involved in the breaking of the sound barrier.

Now, he and the engineers on his team believed, GE would show that it still could be a world leader in manufacturing. But, like him, his engineers were new to compressors. "John figured you didn't need previous compressor-design experience to design a new compressor," one associate says. Mr. Truscott, who retired last year, declined to be interviewed.

Moreover, the team he assembled was convinced that it didn't need outside help. Mr. Magaziner, the consultant, had recommended that the design be joint-ventured with a Japanese producer that already had a refrigerator rotary on the market. Mr. Truscott rejected that idea.

The team also rejected help from Milton Kosfeld, who, as a GE design engineer in the 1950s, had invented the rotary for air conditioners. He left GE in 1969, but in 1983, before joining his present employer, Bristol Compressors of Bristol, Va., he offered his consulting services to the design team. They declined, writing him that "they had sufficient technical expertise," he says.

Limited testing of a compressor prototype began in 1982. Within a year of getting the board's final go-ahead in September 1983, the evaluation engineers had "life tested" about 600 compressors. In the fall of 1984, when 20 senior executives met to review the test data, there wasn't a single documented failure. "It looked too good to be true," recalls James Lehman, a finance official who attended the meeting.

It was. If they had known what some technicians knew, they wouldn't have been so sanguine. Though the compressors hadn't failed, they didn't look right, either, according to one of the technicians, Paul Schank. He had worked in the Louisville testing lab for more than 30 years - and knew compressors. After running the compressors continuously for about two months - under temperatures and pressures supposedly simulating five years' operating life - Mr. Schank would disassemble them and inspect the parts.

About 15% of them, he says, were suspect: Copper windings on the motor were discolored, a sign of excessive heat. Bearing surfaces appeared worn. And some small parts had a black, oily crust - evidence, he thought, that high heat was breaking down the sealed lubricating oil.

Mr. Schank's direct supervisors - a total of four in three years - discounted the findings and apparently didn't relay them up the chain of command. They believed in the basic air-conditioner design and thought the tests far exceeded field conditions. But Mr. Schank contends that the supervisors didn't have the proper technical background to ask the right questions and didn't want to do anything that might derail so big a project.

`The bottom line was that GE would save massive sums of money on each new compressor, and, if they brought the project in on schedule, they'd look like heroes," he says. Adds Robert Derman, who worked with Mr. Schank: "The pressure to get this project done was enormous. It was an awfully big task, and there just wasn't enough time to do it right."

Others involved in the project dispute that, but nearly all agree that the pressure to produce influenced the test results. Although GE offered a five-year warranty on the refrigerator 's cooling system, it couldn't wait for five years of testing. But "life testing" - simulating harsh conditions - can be a tricky guide to a new product's future reliability. In the past, GE had always supplemented such estimates with extensive field testing. This time, field testing was curtailed. The original plan, to put models in the field for two years, was revised to about nine months as managers raced to keep up with their schedules.

"Nobody liked the idea that we weren't getting the proper field exposure," one engineer says. "But it would have taken a lot of courage to tell Welch that we had slipped off schedule."

Meanwhile Mr. Stanton, the retired engineer, was hired as a consultant to evaluate the testing. He considered the tests suspect, he says, because only one compressor had failed in two years - an extraordinarily low number. He says he recommended to a management committee that the test conditions be intensified. But "they didn't want to embark on a new program at that point," he says.

In the end, the schedule was met. By March 1986, some 2 1/2 years after board approval, the Tennessee factory was turning out rotary compressors at a rate of one every six seconds, an amazing feat given the manufacturing tolerances. Later that year, Mr. Blunt, the chief manufacturing engineer, passed out coffee mugs to hundreds of Louisville colleagues to commemorate production of the 1,000,000th compressor.

Consumers, too, were pleased. They snapped up the new models, which featured other innovations, such as a refreshment center in the door. In 1986, GE's market share in refrigerators shot up two full percentage points to about 30%, its best showing in years.

But in July 1987, a bad omen: The first refrigerator - in an unventilated closet in Philadelphia - failed after little more than one year. At first, executives thought it was a fluke. Then, they got reports of failures in Puerto Rico. A team of technicians investigated. By Labor Day, Louisville knew it had a big problem. Over the next few months, as the toll of failed refrigerators mounted, GE engineers worked furiously, often through the night, trying to diagnose the malady.

By December, they still lacked satisfactory answers. So, Mr. Schipke, then the appliance-division chief, pulled the plug on the new compressor. The news, one manufacturing engineer says, literally made him sick. "How do you think the engineers at Thiokol felt when the Challenger blew up?" he asks.

GE scoured the globe for compressors. They weren't easy to find. Ultimately, GE had to persuade one U.S. manufacturer that had quit the business, Tecumseh Products Co., to get back into it. And it provided Tecumseh with GE-built motors, airlifted from Singapore. GE also had to fly Japanese compressors to Louisville.

Perhaps just as disheartening, the new factory worked fine. Only the design had failed. By the summer of 1988, the team investigating the failure rendered its verdict: The two powdered-metal parts were wearing excessively, burning up the oil and eventually choking off all cold air to the refrigerator .

With the problem identified, managers acted swiftly to correct it and, in the process, sidestepped a potentially devastating blow to GE's refrigerator business. Buyers of the refrigerators - some units cost $2,000 - were made whole; the compressors were replaced, usually even before the customers knew anything was wrong.

So far, the company says, not a single lawsuit has been filed against it. In fact, GE's U.S. market share in refrigerators rose during the 1980s, according to Appliance magazine, as the company widened its lead over No. 2 Whirlpool. The Tennessee factory was kept running, though at half its rated capacity, through a contract to supply Fedders Corp. with air-conditioning compressors.

Meanwhile, GE has redesigned the compressor, abandoned powdered-metal parts and developed new lubricants. It also changed its testing procedures. GE says it plans to bring the new compressor back into limited production this fall. The man now in the hot seat, division engineering manager Mark Schreck, says he's "absolutely convinced we've got a high quality compressor. Wouldn't you be in my circumstances?"

## The Saga of the Rotary Compressor

FALL 1981: GE appliance division in Louisville, Ky., hires consultant Ira Magaziner to investigate its refrigerator business.

MAY '82: Chief design engineer John Truscott assembles team to design a new compressor, the rotary.

SEPT '83: Mr. Truscott, fellow engineer Tom Blunt and divison head Roger Schipke present idea to GE Chairman Jack Welch and get authorization for $120 million factory.

FALL '84: Twenty top executives convene for meeting; they review test data and, finding no failures, authorize production.

MARCH '86: Full-scale production starts.

JULY '87: First failure in Philadelphia.

DEC. '87: Mr. Schipke announces decision to drop the compressor and use purchased units, mostly foreign made.

JAN. '88: Changeover to purchased compressors begins.

SUMMER '88: Investigators figure out the cause of the problem.

MARCH '89: GE reveals $450 million pretax charge for fixing the compressor.
