---
title: "Reliability Overview Handout"
author: "Robert A. Stevens"
date: "Monday, December 08, 2014"
output: pdf_document
---

## Selling Reliability to Upper Management

by G.J. Hahn, N. Doganaksoy and W.Q. Meeker, *Quality Progress*, May 1999, pp. 135

An effective reliability improvement program involves more than statistics.  A key ingredient is to gain management support to create a reliability improvement program as part of product design and development.  Consider these ideas when presenting a reliability improvement program to your senior management: 

- Reliability, or external quality improvement, is a key element to quality improvement
    + It is often the part of quality that affects customers the most

- It may be difficult to find problems during early reliability analyses
    + Once those problems are identified, however, it is relatively inexpensive to fix them
    + Discovering problems later, especially after product release, may be easy - but fixing them can be extremely expensive

-	To achieve reliability improvement it is essential that management insist on a comprehensive reliability improvement program at the product design stage
    + This includes tools such as failure modes and effects analysis, fault trees, reliability design reviews, and so forth

-	Specialized statistical tools previously used for reliability demonstration and problem assessment can be leveraged for reliability improvement

-	The tools are only as good as the available data
    +	Thus, a key element of proactive reliability improvement is planning to get the right data
    + This can involve ensuring that degradation information and data on root causes of failures are obtained, at least on a sample of product, and that appropriate accelerated testing is conducted

## Summary of "Reliability Improvement:  Issues and Tools"

by N. Doganaksoy, G.J. Hahn and W.Q. Meeker, *Quality Progress*, June 2000, pp. 115

- Product reliability is the ability of the product to satisfactorily perform its designated function over its customer-intended lifetime

- Modern reliability improvement calls for proactive steps

- Specialized statistical tools are needed to handle unfailed units, non-normal distributions, estimation of low percentiles and extrapolation beyond the range of the data

- The hazard rate is a useful metric, representing the instantaneous failure rate

- The Weibull distribution is a popular and highly useful model for product life data - but it does not fit all situations

- Beware of extrapolations beyond the range of the data

- Analyze multiple failure modes and different product groups individually

## Additional Information

### Web Links

NIST Engineering Statistics Handbook Chapter 8:  Reliability

http://www.itl.nist.gov/div898/handbook/ 

ReliaSoft:  Weibull++, ALTA, other resources and excellent source of information

http://www.reliasoft.com/

WinSmith, other resources and articles

http://www.barringer1.com/index.shtml

### General Journal Articles

"Pitfalls and Practical Considerations in Product Life Analysis - Part I:  Basic Concepts and Dangers of Extrapolation" by G.J. Hahn and W.Q. Meeker, *Journal of Quality Technology*, Vol. 14, No. 3, pp. 144-152

"Pitfalls and Practical Considerations in Product Life Analysis - Part II:  Mixtures of Product Populations and More General Models" by G.J. Hahn and W.Q. Meeker, *Journal of Quality Technology*, Vol. 14, No. 4, pp. 177-185

"Product Life Data Analysis:  A Case Study" by N. Doganaksoy, G.J. Hahn and W.Q. Meeker,  *Quality Progress*, June 2000, pp. 115-122

"Reliability Analysis by Failure Mode" by N. Doganaksoy, G.J. Hahn, and W.Q. Meeker, *Quality Progress*, June 2002, pp. 47-52 

"Reliability Improvement:  Issues and Tools" by G.J. Hahn, N. Doganaksoy and W.Q. Meeker, *Quality Progress*, May 1999, pp. 133-139

### General Books

*Applied Life Data Analysis* by Wayne Nelson

*Applied Reliability* by P.A. Tobias and D.C. Trindade

*Handbook of Reliability Engineering and Management* by W.G. Ireson, C.F. Coombs and R.Y. Moss, editors

*Practical Reliability Engineering* by P.D.T. O'Connor

*Statistical Methods for Reliability Data* by W.Q. Meeker and L.A. Escobar

*Statistical Models and Methods for Lifetime Data* by J.F. Lawless

*The New Weibull Handbook* by R.B. Abernethy

### Accelerated Life Testing and HALT

*Accelerated Reliability Engineering - HALT AND HASS* by G.K. Hobbs

*Accelerated Testing:  Statistical Models, Test Plans, and Data Analysis* by W. Nelson

"Speedier Reliability Analysis" by G.J. Hahn, W.Q. Meeker and N. Doganaksoy, *Quality Progress*, June 2003, pp. 58-64

"Using Degradation Data for Product Liability Analysis" by W.Q. Meeker, N. Doganaksoy, and G. J. Hahn, *Quality Progress*, June 2001, pp. 60-65

### Robust and other designed experiments

*Quality Engineering Using Robust Design* by M.S. Phadke

*Reliability Improvement with Design of Experiments* by L.W. Condra

"Using Statistically Designed Experiments to Improve Reliability and to Achieve Robust Reliability" by M. Hamada, *IEEE Transactions on Reliability*, Vol. 44, 1995, p. 206. 
